apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: "domain.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: deployment
            port:
              number: 80
  - host: "mongo.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mongo
            port:
              number: 27017
