apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-flask-app
spec:
  rules:
  - host: "domain.com"
    http:
      paths:
      - pathType: Prefix
        path: "/test"
        backend:
          service:
            name: flask-app
            port:
              number: 5000
  - host: "*.domain.com"
    http:
      paths:
      - pathType: Prefix
        path: "/test"
        backend:
          service:
            name: flask-app
            port:
              number: 5000
